const activitiesList = [
  {
    id: 1,
    eventID: 1,
    name: "Basketball",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque pariatur, ab mollitia non quo quis laborum minima maiores eius ratione distinctio, libero, nihil repellendus repellat aliquam. Necessitatibus dicta velit iure.",
    points: 10,
    attended: false,
    location: "Gym",
    startDate: "2025-11-25T08:00:00",
    endDate: "2025-11-25T15:00:00",
  },
  {
    id: 2,
    eventID: 1,
    name: "Volleyball",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque pariatur, ab mollitia non quo quis laborum minima maiores eius ratione distinctio, libero, nihil repellendus repellat aliquam. Necessitatibus dicta velit iure.",
    points: 10,
    attended: false,
    location: "Gym",
    startDate: "2025-11-25T08:00:00",
    endDate: "2025-11-25T15:00:00",
  },
  {
    id: 3,
    eventID: 2,
    name: "Act1 for event 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque pariatur, ab mollitia non quo quis laborum minima maiores eius ratione distinctio, libero, nihil repellendus repellat aliquam. Necessitatibus dicta velit iure.",
    points: 10,
    attended: true,
    location: "Gym",
    startDate: "2025-11-25T07:00:00",
    endDate: "2025-11-25T15:00:00",
  },
  {
    id: 4,
    eventID: 2,
    name: "Act2 for event 2",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque pariatur, ab mollitia non quo quis laborum minima maiores eius ratione distinctio, libero, nihil repellendus repellat aliquam. Necessitatibus dicta velit iure.",
    points: 10,
    attended: false,
    location: "Gym",
    startDate: "2025-11-25T08:00:00",
    endDate: "2025-11-25T15:00:00",
  },
  {
    id: 5,
    eventID: 3,
    name: "Act1 for event 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque pariatur, ab mollitia non quo quis laborum minima maiores eius ratione distinctio, libero, nihil repellendus repellat aliquam. Necessitatibus dicta velit iure.",
    points: 10,
    attended: false,
    location: "Gym",
    startDate: "2025-11-25T08:00:00",
    endDate: "2025-11-25T15:00:00",
  },
  {
    id: 6,
    eventID: 3,
    name: "Act2 for event 3",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Doloremque pariatur, ab mollitia non quo quis laborum minima maiores eius ratione distinctio, libero, nihil repellendus repellat aliquam. Necessitatibus dicta velit iure.",
    points: 10,
    attended: false,
    location: "Gym",
    startDate: "2025-11-25T08:00:00",
    endDate: "2025-11-25T15:00:00",
  },
];

export default activitiesList;
